### ISSUE TITLE
mirror.envygeeks.io is Down

### ISSUE THREAD

**Issue by suskind** [envygeeks/docker#12]
FROM jekyll/jekyll:3.2.1 

that uses `envygeeks/alpine`

is failing when fetching: 
 
http://mirror.envygeeks.io/alpine/v3.5/main/x86_64/APKINDEX.tar.gz

**Comment by envygeeks** [comment]
I know at this point that my DNS is resolving: `dig envygeeks.io +noedns @ns-cloud-e1.googledomains.com` but I am working out with my domain provider as to what's going on, I'll update in a minute.

**Comment by suskind** [comment]
it's working 

thank you

You can close this issue

**Comment by envygeeks** [comment]
This mirror has been shutdown for months, closing this out.
