### ISSUE TITLE
timezone data missing

### ISSUE THREAD

**Issue by zym1010** [envygeeks/docker#3]
This is a copy of the issue https://github.com/jekyll/docker/issues/87.

***

It seems that the timezone feature in Jekyll (at least for the one in pages tag) needs package tzdata to work properly; otherwise, the timezone shown in the generated website is always GMT.

I tried to fix this in my own image https://hub.docker.com/r/leelabcnbc/lab-website/~/dockerfile/, and I hope this can be done in the base image (at least for pages), since timezone works properly on GitHub, but not on Docker image, which is somehow inconsistent the purpose of this Docker image.

**Comment by envygeeks** [comment]
This has been resolved internally and will be pushed up to this repo in the next few days, however at this time the latest Ubuntu/Alpine images both contain TZData.

Thanks for reporting this issue!
