### ISSUE TITLE
SMTP/Developer Emails error on container start

### ISSUE THREAD

**Issue by kotowick** [envygeeks/docker#4]
Getting the following message when starting the Discourse container:

"You have not setup SMTP or Developer Emails, please set them up."

Any ideas?

**Comment by envygeeks** [comment]
You need to set `DISCOURSE_DEVELOPER_EMAILS` in your environment to an email you wish to allow to be the defacto super-admin who has access to everything by default when registering.

**Comment by envygeeks** [comment]
This issue is being closed from lack of response.  If you continue to have a problem please update.

**Comment by EarMaster** [comment]
This is still an issue. I downloaded the container using Kinematic and there is no indication or documentation (apart from this issue) what I need to do to fix this.

![image](https://cloud.githubusercontent.com/assets/1247035/14980283/d7a217ee-1127-11e6-9f56-cb110e30b793.png)

I've set `DISCOURSE_DEVELOPER_EMAILS` in the environment, but the error still persists.

**Comment by envygeeks** [comment]
@EarMaster I'll reopen

**Comment by envygeeks** [comment]
@EarMaster @kotowick I don't know what Kinematic could be doing differently than our Docker-Compose driven Kubernetes setup but I'll try and figure out what's going on in the next few days and see if I can resolve it within my image or otherwise file an link an upstream ticket.

**Comment by EarMaster** [comment]
Thanks a lot. If I can provide you any information, please ask.

**Comment by envygeeks** [comment]
We recently updated our images to clarify the error messages: https://github.com/envygeeks/docker/commit/b7a07c82b74d0fcb6c30bbf8bcde60572b9071b9 can both of you confirm that you provide those variables?

**Comment by EarMaster** [comment]
I did not provide DISCOURSE_SMTP_ADDRESS in the first place. Now after I did (to "localhost"), it is starting up. Thanks for pointing this out.

**Comment by envygeeks** [comment]
Closing this out since it works for you @EarMaster, and since @kotowick hasn't responded I'll assume it's fixed there too.  Thanks for the update!
