### ISSUE TITLE
Could not find i18n-0.7.0 in any of the sources

### ISSUE THREAD

**Issue by TravisTam** [envygeeks/docker#8]
After I start it from docker it shows "Could not find i18n-0.7.0 in any of the sources". And then quit the docker start.

**Comment by envygeeks** [comment]
Which image? `envygeeks/discourse` is the only one I can think of that would throw that error.

**Comment by TravisTam** [comment]
yes, do you know what happen?

**Comment by envygeeks** [comment]
@TravisTam I don't as that dependency is supplied upstream but I'll look into it.
